#!/usr/bin/env python3
"""Generate nethack_harness/monsters.py, the monster facts the loop uses, from a NetHack source tree.

    python3 tools/gen_monsters.py /path/to/NetHack > nethack_harness/monsters.py

For each monster it keeps only what the loop needs: class letter, colour, level, speed, and the most damage
it can deal the hero in one hero turn, in melee and at range (attack dice at their maximum, a wielded weapon
counted as d8, times the attacks it gets per hero turn at speed 12).

It also writes CORPSES: what eating each monster's corpse does, as flag letters (see CORPSE_FLAGS).
"""
import os
import re
import sys

# Game colours as the screen shows them: (base colour, bright).
CLR = {"CLR_BLACK": ("blue", False), "CLR_RED": ("red", False), "CLR_GREEN": ("green", False),
       "CLR_BROWN": ("brown", False), "CLR_BLUE": ("blue", False), "CLR_MAGENTA": ("magenta", False),
       "CLR_CYAN": ("cyan", False), "CLR_GRAY": ("gray", False), "CLR_ORANGE": ("red", True),
       "CLR_BRIGHT_GREEN": ("green", True), "CLR_YELLOW": ("brown", True), "CLR_BRIGHT_BLUE": ("blue", True),
       "CLR_BRIGHT_MAGENTA": ("magenta", True), "CLR_BRIGHT_CYAN": ("cyan", True), "CLR_WHITE": ("gray", True)}
# Corpse facts as flag letters: a acidic, p poisonous, w lycanthrope, h human, e elf, d dwarf, g gnome, o orc,
# m domestic (aggravates monsters when eaten), n leaves no corpse.
CORPSE_FLAGS = (("M1_ACID", "a"), ("M1_POIS", "p"), ("M2_WERE", "w"), ("M2_HUMAN", "h"), ("M2_ELF", "e"),
                ("M2_DWARF", "d"), ("M2_GNOME", "g"), ("M2_ORC", "o"), ("M2_DOMESTIC", "m"), ("G_NOCORPSE", "n"))
RANGED = ("AT_BREA", "AT_SPIT", "AT_GAZE", "AT_MAGC")
SKIP = ("AT_NONE", "AT_BOOM")          # passive and death explosions do not hit an attacker's turn
# Damage types that cost no hit points directly (they blind, stun, steal, teleport, rust ...).
NO_HP = ("AD_BLND", "AD_SLEE", "AD_STON", "AD_TLPT", "AD_SGLD", "AD_SITM", "AD_SEDU", "AD_HALU", "AD_CONF",
         "AD_STUN", "AD_SLOW", "AD_PLYS", "AD_DREN", "AD_RUST", "AD_CORR", "AD_DCAY", "AD_ENCH", "AD_STCK",
         "AD_LYCA", "AD_POLY", "AD_CURS", "AD_SSEX", "AD_SPC1", "AD_SPC2", "AD_WERE")


def main(src):
    defsym = open(os.path.join(src, "include", "defsym.h")).read()
    letters = {m.group(2): m.group(1) for m in re.finditer(r"MONSYM\(\s*\d+,\s*'(.)',\s*\w+,\s*(S_\w+)", defsym)}
    letters["S_invisible"] = "I"
    alias = dict(re.findall(r"#define (HI_\w+)\s+(CLR_\w+)", open(os.path.join(src, "include", "color.h")).read()))
    text = open(os.path.join(src, "include", "monsters.h")).read()
    out = {}
    for m in re.finditer(r"MON\((?:NAM|NAMS)\(\"([^\"]+)\".*?\),\s*(S_\w+),\s*LVL\((-?\d+),\s*(\d+),.*?\),.*?"
                         r"A\((.*?)\),\s*SIZ\(.*?\),.*?,\s*(\w+(?:\s*\|\s*\w+)?),\s*\w+\)", text, re.S):
        name, sym, level, speed, attacks, colour = m.groups()
        melee = ranged = 0
        for at, ad, n, d in re.findall(r"ATTK\((\w+),\s*(\w+),\s*(\d+),\s*(\d+)\)", attacks):
            if at in SKIP or ad in NO_HP:
                continue
            most = int(n) * int(d) + (8 if at == "AT_WEAP" else 0)
            if at in RANGED:
                ranged += most
            else:
                melee += most
        per_turn = max(1, -(-int(speed) // 12)) if int(speed) else 0
        colour = CLR.get(alias.get(colour.strip(), colour.strip()), ("gray", False))
        out[name] = (letters.get(sym, "?"), colour[0], colour[1], int(level), int(speed), melee * per_turn,
                     ranged * per_turn)
    print('"""Monster facts generated by tools/gen_monsters.py from the NetHack source: name -> (class letter,')
    print('base colour, bright, level, speed, most melee damage per hero turn, most ranged damage per hero turn).')
    print('')
    print('CORPSES: name -> flag letters for what eating its corpse means: a acidic, p poisonous, w lycanthrope,')
    print('h human, e elf, d dwarf, g gnome, o orc, m domestic, n leaves no corpse. Monsters with no flag are left out."""')
    print("MONSTERS = {")
    for name in sorted(out):
        print("    %r: %r," % (name, out[name]))
    print("}")
    print("CORPSES = {")
    flags = corpse_flags(text)
    for name in sorted(flags):
        print("    %r: %r," % (name, flags[name]))
    print("}")


def corpse_flags(text):
    """name -> flag letters, from each MON() entry's generation flags and M1/M2 flags. Every name of a monster
    with male, female and neutral names is listed (a corpse may be named by any of them)."""
    out = {}
    for entry in re.split(r"\bMON\(", text)[1:]:
        m = re.match(r"\s*NAMS?\(([^)]*)\)", entry)
        if not m:
            continue
        names = re.findall(r'"([^"]+)"', m.group(1))
        head = entry.split("SIZ(", 1)
        if len(head) < 2:
            continue
        words = set(re.findall(r"\b[MG][12_]?\w*", head[0] + head[1].split(")", 1)[1]))
        letters = "".join(ch for flag, ch in CORPSE_FLAGS if flag in words)
        for name in names:
            got = out.get(name, "") + letters
            if got:
                out[name] = "".join(ch for _, ch in CORPSE_FLAGS if ch in got)
    return out


if __name__ == "__main__":
    main(sys.argv[1])
